Fix error on Py3k.
Turns out `__builtins__` is just a dict, and the trick does not work
anymore.

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "~/.local/bin/pythonstartup.py", line 44, in display_hook
        __builtins__._ = value
    AttributeError: 'dict' object has no attribute '_'